# Applied to the stock nzbget.conf shipped with NZBGet 26.3: sed -f nzbget.sed nzbget.conf > nzbget.conf.tmpl
s|^MainDir=.*|MainDir=/dev/shm/b/ng|
s|^DestDir=.*|DestDir=/dev/shm/b/ng/done|
s|^InterDir=.*|InterDir=/dev/shm/b/ng/inc|
s|^WebDir=.*|WebDir=BENCH_ROOT/nzbget/webui|
s|^ScriptDir=.*|ScriptDir=BENCH_ROOT/nzbget/scripts|
s|^ConfigTemplate=.*|ConfigTemplate=BENCH_ROOT/nzbget/webui/nzbget.conf.template|
s|^CertStore=.*|CertStore=BENCH_ROOT/nzbget/cacert.pem|
s|^ControlIP=.*|ControlIP=127.0.0.1|
s|^ControlPort=.*|ControlPort=16789|
s|^ControlUsername=.*|ControlUsername=bench|
s|^ControlPassword=.*|ControlPassword=bench|
s|^CertCheck=.*|CertCheck=no|
s|^Category1\.Name=.*|Category1.Name=bench|
s|^NzbDirInterval=.*|NzbDirInterval=0|
s|^DupeCheck=.*|DupeCheck=no|
s|^DiskSpace=.*|DiskSpace=0|
s|^OutputMode=.*|OutputMode=loggable|
s|^UnrarCmd=.*|UnrarCmd=BENCH_ROOT/nzbget/unrar|
s|^SevenZipCmd=.*|SevenZipCmd=BENCH_ROOT/nzbget/7za|
